/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  guides: [    
    {
      type: "category",
      label: "Quick Start Guides",
      collapsed: false,
      items: [
        { type: 'doc', label: "Guides List Introduction",  id: "guides/en/guides_list"  },
        {
          type: "category",
          label: "Creating and using wallets",
          collapsed: false,
          items: [
            { type: "link", 
              label: "How to Get Testnet CFX", 
              href: "https://developer.confluxnetwork.org/guides/en/how_to_use_cfx_faucet" 
            },
            { type: "link", 
              label: "Getting Started with MetaMask", 
              href: "https://developer.confluxnetwork.org/guides/en/user_metamask_interact_evmspace" 
            },
            { type: "link", 
              label: "Conflux eSpace Guide", 
              href: "https://developer.confluxnetwork.org/v2-hardfork/evm_space_guide" 
            },
            { type: "link", 
              label: "Ledger Wallet", 
              href: "https://developer.confluxnetwork.org/sdks-and-tools/en/using_ledger_on_core" 
            },
            { type: "link", 
              label: "Transfer CFX to eSpace", 
              href: "https://evm.fluentwallet.com/" 
            },
            { type: "link", 
              label: "Fluent Wallet Docs", 
              href: "https://fluent-wallet.zendesk.com/hc/en-001" 
            },
          ]
        },
        {
          type: "category",
          label: "Understanding the basics ",
          collapsed: false,
          items: [
            { type: "link", 
              label: "Easy to understand introduction Of Tree Graph", 
              href: "https://medium.com/conflux-network/understanding-the-conflux-tree-graph-consensus-algorithm-e1b57d5c3da9" 
            },
            { type: "link", 
              label: "Conflux Network: Engineering An Economic Design", 
              href: "https://confluxnetwork.org/files/Conflux_Economic_Paper_20201230.pdf" 
            },
          ]
        },
        {
          type: "category",
          label: "Developing using CONFLUX",
          collapsed: false,
          items: [
            { type: "link", 
              label: "How to Quickly Deploy a CRC20 Token", 
              href: "https://developer.confluxnetwork.org/guides/en/how_to_deploy_erc20_token" 
            },
            { type: "link", 
              label: "SDKs", 
              href: "https://developer.confluxnetwork.org/sdks-and-tools/en/conflux_sdks" 
            },
            { type: "link", 
              label: "Tools", 
              href: "https://developer.confluxnetwork.org/sdks-and-tools/en/conflux_tools" 
            },
            { type: "link", 
              label: "Introduction to Smart Contracts", 
              href: "https://developer.confluxnetwork.org/contract/en/contract_introduction" 
            },
            { type: "link", 
              label: "Solidity Tutorial", 
              href: "https://confluxnetwork365-my.sharepoint.com/:w:/g/personal/luis_miguel_confluxnetwork_org/EX3TjDKiC4pJtPdHYWrvaacBzi08qE0u9SE9_4XtEOtPWQ?e=7PZNQy" 
            },
            { type: "link", 
              label: "NFTs Minting and Contract Interaction", 
              href: "https://docs.google.com/document/d/1ijsf5QfnxPq7DHOFCPIJKlcD7VomqUFDbUEWyuwKmxM" 
            },            
          ]
        },
        {
          type: "category",
          label: "Staking",
          collapsed: false,
          items: [
            { type: "link", 
              label: "Eth2Stake - The PoS Staking Guide for Ethereans ", 
              href: "https://forum.conflux.fun/t/eth2stake-the-pos-staking-guide-for-ethereans-bridging-eth-for-staking-on-conflux-pos/13839" 
            },
            { type: "link", 
              label: "From Binance CFX (bCFX) to PoS Staking on Conflux", 
              href: "https://medium.com/@cfx_miguel/from-bcfx-to-pos-staking-on-conflux-dca0df638233" 
            },
            { type: "link", 
              label: "PoS Pool Economics (APY)", 
              href: "https://forum.conflux.fun/t/the-beavers-guide-to-calculating-block-rewards-when-staking-in-the-pos-finality-chain/13900" 
            },
          ]
        },
        {
          type: "category",
          label: "Mining",
          collapsed: false,
          items: [
            { type: "link", 
              label: "Get Conflux Client", 
              href: "https://developer.confluxnetwork.org/run-a-node/en/how_to_get" 
            },
            { type: "link", 
              label: "Run a Node", 
              href: "https://developer.confluxnetwork.org/conflux-doc/docs/get_started" 
            },
            { type: "link", 
              label: "How to Start a Fullnode Tutorial", 
              href: "https://forum.conflux.fun/t/how-to-start-a-fullnode-tutorial-conflux-v2-0-0-fix/13471" 
            },
            { type: "link", 
              label: "PoS Registration Tutorial", 
              href: "https://forum.conflux.fun/t/pos-registration-tutorial-conflux-v2-0-0-fix/13469" 
            },
            { type: "link", 
              label: "Launching an AWS instance for a PoS Pool", 
              href: "https://forum.conflux.fun/t/running-a-pos-node-on-aws-server-setup-node-configuration/13998" 
            },
            { type: "link", 
              label: "Configuring PoS Node + Launching PoS Pool", 
              href: "https://developer.confluxnetwork.org/run-a-node/en/pos_staking/" 
            },
          ]
        },
        {
          type: "category",
          label: "Using ecosystem tools",
          collapsed: false,
          items: [
            { type: "link", 
              label: "ShuttleFlow", 
              href: "https://forum.conflux.fun/t/shuttleflow-v1-4-0-tutorial-token-captain-removed/9214" 
            },
          ]
        }        
      ]
    }
  ],

  docs: [
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      items: [
        { type: "doc", id: "introduction/en/conflux_overview" },
        {
          type: "doc",
          id: "introduction/en/conflux_basics",
        },
        {
          type: 'doc',
          label: 'Internal Contracts',
          id: "conflux-rust/internal_contract/internal_contract",
        },
        {
          type: 'doc',
          id: 'introduction/en/conflux_storage'
        },
        {
          type: "doc",
          id: 'introduction/en/conflux_papers',
        }, 
        {
          type: "doc",
          id: "sdks-and-tools/en/conflux_rpcs",
          label: "Public RPC Endpoints"
        },
        {
          type: 'link',
          label: 'Testnet Faucet',
          href: 'https://faucet.confluxnetwork.org/'
        }
      ],
    },
    {
      type: "category",
      label: "Hardfork Hydra(v2.0)",
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'v2-hardfork/hydra_overview'
        },
        {
          type: 'doc',
          id: 'v2-hardfork/pos_overview'
        },
        {
          type: 'doc',
          id: 'v2-hardfork/why_pos'
        },
        {
          type: 'doc',
          id: 'v2-hardfork/pos_faqs'
        },
        {
          type: 'doc',
          id: 'v2-hardfork/new_introduced_contracts'
        }
      ]
    },
    {
      type: "category",
      label: "Hardfork v2.1",
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'v2.1-hardfork/hardfork_v2.1.0_overview'
        }
      ]
    },
    {
      type: "category",
      label: "Run Conflux Node",
      collapsed: false,
      items: [
        { type: 'doc', id: 'run-a-node/en/how_to_get' },
        { type: "doc", id: "conflux-doc/docs/installation" },
        { type: "doc", id: "conflux-doc/docs/get_started" },
        {
          type: "doc",
          id: "conflux-doc/docs/independent_chain",
        },
        {
          type: "doc",
          id: "conflux-doc/docs/light_node",
        },
        { type: "doc", id: "apis/en/node_config_example" },
        { type: "doc", id: "run-a-node/en/official_bootnodes" },
        {
          type: 'link',
          label: 'Run a Miner',
          href: 'https://forum.conflux.fun/t/conflux-tethys-gpu-mining-instruction-v1-1-3/3775'
        },
        {
          type: 'link',
          label: 'Archivenode snapshot',
          href: 'https://github.com/conflux-fans/archive-tool'
        },
      ],
    },
    {
      type: "category",
      label: "Sending Transaction",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "conflux-doc/docs/send_transaction",
        },
        {
          type: "doc",
          id: "sending-tx/en/transaction_explain",
        },
        {
          type: "doc",
          id: "sending-tx/en/transaction_stage",
        },
        {
          type: "doc",
          id: "sending-tx/en/why_tx_is_pending",
        },
        {
          type: "doc",
          label: "Common Errors",
          id: "sending-tx/en/transaction_send_common_error",
        },
        {
          type: "doc",
          label: 'FAQs',
          id: "sending-tx/en/transaction_faqs",
        },
      ],
    },
    {
      type: "category",
      label: "Smart Contract",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "contract/en/contract_introduction",
        },
      ],
    },
    {
      type: "category",
      label: "SDKs and Tools",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "sdks-and-tools/en/conflux_sdks",
        },
        {
          type: "doc",
          id: "sdks-and-tools/en/conflux_tools",
        },
        {
          type: "doc",
          id: "sdks-and-tools/en/using_ledger_on_core",
          label: 'Ledger Wallet'
        },
      ],
    },
    {
      type: 'link',
      label: 'Fluent Wallet Docs',
      href: 'https://fluent-wallet.zendesk.com/hc/en-001'
    },
    {
      type: 'link',
      label: 'Shuttleflow Docs',
      href: 'https://conflux-dev.github.io/conflux-dex-docs/shuttleflow/'
    },
    {
      type: 'link',
      label: 'Conflux-rust Changelog',
      href: 'https://github.com/Conflux-Chain/conflux-rust/blob/master/changelogs/CHANGELOG-1.1.x.md'
    }
  ],

  evmSpace: [
    { type: 'doc', id: 'conflux-doc/docs/EVM-Space/intro_of_evm_space' },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        { type: 'doc', id: 'conflux-doc/docs/EVM-Space/evm_space_networks' },
        { 
          type: 'doc', 
          id: 'v2-hardfork/evm_space_guide',
          label: 'eSpace Guide'
        },
      ]
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        { 
          type: 'doc', 
          id: 'guides/en/user_metamask_interact_evmspace',
          label: 'MetaMask'
        }, {
          type: 'doc',
          id: 'guides/en/using_ledger_on_espace',
          label: 'Ledger Hardware Wallet'
        },
        { 
          type: "link", 
          label: "eSpace Faucet",
          href: "https://efaucet.confluxnetwork.org"
        }
      ]
    },
    {
      type: 'category',
      label: 'Bridges',
      collapsed: false,
      items: [
        { 
          type: 'doc', 
          id: 'conflux-doc/docs/EVM-Space/account_explain',
          label: 'Address Explain'
        }
        , { 
          type: 'doc', 
          id: 'conflux-doc/docs/EVM-Space/cross_space_call',
          label: 'CrossSpaceCall'
        },
        { 
          type: "link", 
          label: "Mainnet Space Bridge",
          href: "https://evm.fluentwallet.com/"
        },
      ]
    },
    {
      type: 'category',
      label: 'Compatibility',
      collapsed: false,
      items: [
        { 
          type: 'doc', 
          id: 'conflux-doc/docs/EVM-Space/evm_space_rpc_compatibility',
          label: 'JSON-RPC'
        },
        { 
          type: 'doc', 
          id: 'conflux-doc/docs/EVM-Space/evm_space_vm_compatibility',
          label: 'EVM'
        },
      ]
    },
    {
      type: 'category',
      label: 'Other',
      collapsed: false,
      items: [
        
      ]
    }
  ],

  api: [
    {
      type: "category",
      label: "JSON-RPCs",
      items: [
        { type: "doc", id: "conflux-doc/docs/json_rpc" },    
        { type: "doc", id: "conflux-doc/docs/RPCs/txpool_rpc" },
        { type: "doc", id: "conflux-doc/docs/RPCs/pos_rpc" },
        { type: "doc", id: "conflux-doc/docs/RPCs/debug_rpc" },
        { type: "doc", id: "conflux-doc/docs/RPCs/trace_rpc" },
        { type: "doc", id: "conflux-doc/docs/RPCs/common_rpc_error" },
        { type: "doc", id: "conflux-doc/docs/RPCs/send_tx_error" },
      ]
    },{
      type: "category",
      label: "Conflux OPEN-RPCs",
      items: [
        { 
          type: "link", 
          label: "cfx RPC",
          href: "https://playground.open-rpc.org/?uiSchema[appBar][ui:title]=Conflux%20RPC&uiSchema[appBar][ui:logoUrl]=https://avatars.githubusercontent.com/u/46887720&uiSchema[appBar][ui:examplesDropdown]=false&uiSchema[appBar][ui:splitView]=false&schemaUrl=https://raw.githubusercontent.com/darwintree/conflux-openrpc/main/static/conflux-openrpc.json"
        },
        { 
          type: "link", 
          label: "pos RPC",
          href: "https://playground.open-rpc.org/?uiSchema[appBar][ui:title]=Conflux%20RPC&uiSchema[appBar][ui:logoUrl]=https://avatars.githubusercontent.com/u/46887720&uiSchema[appBar][ui:examplesDropdown]=false&uiSchema[appBar][ui:splitView]=false&schemaUrl=https://raw.githubusercontent.com/darwintree/conflux-openrpc/main/static/pos-openrpc.json"
        }    
      ]
    },
    { type: "doc", id: "conflux-doc/docs/pubsub" },
    { type: "doc", id: "conflux-doc/docs/cli_sub_commands" },
    // { type: "doc", id: "apis/en/node_config_example" },
    {
      type: 'category',
      label: 'Internal Contracts API',
      items: [
        {
          type: 'link',
          label: 'AdminControl',
          href: 'https://github.com/Conflux-Chain/conflux-rust/blob/master/internal_contract/contracts/AdminControl.sol'
        },
        {
          type: 'link',
          label: 'SponsorWhitelistControl',
          href: 'https://github.com/Conflux-Chain/conflux-rust/blob/master/internal_contract/contracts/SponsorWhitelistControl.sol'
        },
        {
          type: 'link',
          label: 'Staking',
          href: 'https://github.com/Conflux-Chain/conflux-rust/blob/master/internal_contract/contracts/Staking.sol'
        },
        {
          type: 'link',
          label: 'ConfluxContext',
          href: 'https://github.com/Conflux-Chain/conflux-rust/blob/master/internal_contract/contracts/ConfluxContext.sol'
        },
        {
          type: 'link',
          label: 'PoSRegister',
          href: 'https://github.com/Conflux-Chain/conflux-rust/blob/master/internal_contract/contracts/PoSRegister.sol'
        },
        {
          type: 'link',
          label: 'CrossSpaceCall',
          href: 'https://github.com/Conflux-Chain/conflux-rust/blob/master/internal_contract/contracts/CrossSpaceCall.sol'
        },
        {
          type: 'link',
          label: 'ParamsControl',
          href: 'https://github.com/Conflux-Chain/conflux-rust/blob/master/internal_contract/contracts/ParamsControl.sol'
        },
      ]
    },
    {
      type: "doc",
      id: "introduction/en/conflux_refs",
    },
    {
      type: 'link',
      label: 'CIPs',
      href: 'https://github.com/conflux-chain/cips'
    }
  ],
};
