version: 2.1
workflows:
  deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node@sha256:90e57990e54d3b1cbfbad5a2f2828530cbe9f92bd8dac128487f3067ae966f24
    environment:
      - GIT_USER: ConfluxBot
      - USE_SSH: true
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: Check if there's any markdown file updated, update submodules
          command: |
            ./.circleci/scripts/update-submodules.sh
      - run:
          name: Maybe skip rest if no md file updatd
          command: ./.circleci/scripts/maybe-skip.sh
      - run:
          name: Build
          no_output_timeout: 5m
          command: |
            yarn && yarn build

      - run:
          name: Deploy to github pages
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --recursive $CIRCLE_REPOSITORY_URL project

            mkdir ../project-gh-pages
            cp -r .git ../project-gh-pages
            cd ../project-gh-pages
            git checkout $TARGET_BRANCH

            cp -r ../project/build/* .
            cp -r ../project/.circleci .
            cp -r ../project/CNAME .
            git add -A
            git commit -m "Automated deployment: ${CIRCLE_SHA1} [ci skip]" --allow-empty 1> /dev/null
            git push origin $TARGET_BRANCH
